import type { Metadata } from "next"
import { Roboto } from "next/font/google"
import "./globals.css"
import { Footer } from "./@components/footer"
import { Header } from "./@components/header"

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="pt-BR">
            <body
                className={`${roboto.variable} flex flex-col bg-zinc-950 antialiased`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
